// <auto-generated />
using Globomantics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(HouseDbContext))]
    [Migration("20240826035114_Bids")]
    partial class Bids
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Globomantics.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Bidder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 200000.0,
                            Bidder = "Sonia Reading",
                            HouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 202400.0,
                            Bidder = "Dick Johnson",
                            HouseId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 302400.0,
                            Bidder = "Mohammed Vahls",
                            HouseId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 310500.0,
                            Bidder = "Jane Williams",
                            HouseId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 315400.0,
                            Bidder = "John Kepler",
                            HouseId = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 201000.0,
                            Bidder = "Bill Mentor",
                            HouseId = 3
                        },
                        new
                        {
                            Id = 7,
                            Amount = 410000.0,
                            Bidder = "Melissa Kirk",
                            HouseId = 4
                        },
                        new
                        {
                            Id = 8,
                            Amount = 450000.0,
                            Bidder = "Scott Max",
                            HouseId = 4
                        },
                        new
                        {
                            Id = 9,
                            Amount = 470000.0,
                            Bidder = "Christine James",
                            HouseId = 4
                        },
                        new
                        {
                            Id = 10,
                            Amount = 450000.0,
                            Bidder = "Omesh Carim",
                            HouseId = 5
                        },
                        new
                        {
                            Id = 11,
                            Amount = 150000.0,
                            Bidder = "Charlotte Max",
                            HouseId = 5
                        },
                        new
                        {
                            Id = 12,
                            Amount = 170000.0,
                            Bidder = "Marcus Scott",
                            HouseId = 5
                        });
                });

            modelBuilder.Entity("Globomantics.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Elm St",
                            Country = "USA",
                            Description = "A cozy family home.",
                            Price = 250000.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak St",
                            Country = "USA",
                            Description = "Spacious with a large backyard.",
                            Price = 350000.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine St",
                            Country = "USA",
                            Description = "Modern design, close to downtown.",
                            Price = 500000.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Maple St",
                            Country = "Canada",
                            Description = "Quaint and charming cottage.",
                            Price = 200000.0
                        },
                        new
                        {
                            Id = 5,
                            Address = "202 Birch St",
                            Country = "Canada",
                            Description = "Recently renovated with high-end finishes.",
                            Price = 450000.0
                        },
                        new
                        {
                            Id = 6,
                            Address = "303 Cedar St",
                            Country = "UK",
                            Description = "Historic home with original features.",
                            Price = 600000.0
                        },
                        new
                        {
                            Id = 7,
                            Address = "404 Willow St",
                            Country = "UK",
                            Description = "Contemporary design, energy efficient.",
                            Price = 400000.0
                        },
                        new
                        {
                            Id = 8,
                            Address = "505 Ash St",
                            Country = "Australia",
                            Description = "Beachside property with stunning views.",
                            Price = 750000.0
                        },
                        new
                        {
                            Id = 9,
                            Address = "606 Cherry St",
                            Country = "Australia",
                            Description = "Ideal for families, near schools and parks.",
                            Price = 300000.0
                        },
                        new
                        {
                            Id = 10,
                            Address = "707 Fir St",
                            Country = "Germany",
                            Description = "Traditional German house, well-maintained.",
                            Price = 350000.0
                        },
                        new
                        {
                            Id = 11,
                            Address = "808 Spruce St",
                            Country = "Germany",
                            Description = "Modern apartment in a vibrant area.",
                            Price = 500000.0
                        },
                        new
                        {
                            Id = 12,
                            Address = "909 Poplar St",
                            Country = "France",
                            Description = "Elegant home with classic French architecture.",
                            Price = 650000.0
                        },
                        new
                        {
                            Id = 13,
                            Address = "1010 Linden St",
                            Country = "France",
                            Description = "Charming property with a beautiful garden.",
                            Price = 300000.0
                        },
                        new
                        {
                            Id = 14,
                            Address = "1111 Sequoia St",
                            Country = "Italy",
                            Description = "Rustic villa in the countryside.",
                            Price = 550000.0
                        },
                        new
                        {
                            Id = 15,
                            Address = "1212 Redwood St",
                            Country = "Italy",
                            Description = "Modern apartment with city views.",
                            Price = 400000.0
                        },
                        new
                        {
                            Id = 16,
                            Address = "1313 Oakwood St",
                            Country = "Spain",
                            Description = "Luxury home with a private pool.",
                            Price = 700000.0
                        },
                        new
                        {
                            Id = 17,
                            Address = "1414 Pinewood St",
                            Country = "Spain",
                            Description = "Cozy apartment in a historic building.",
                            Price = 250000.0
                        },
                        new
                        {
                            Id = 18,
                            Address = "1515 Maplewood St",
                            Country = "Japan",
                            Description = "Traditional house with a serene garden.",
                            Price = 450000.0
                        },
                        new
                        {
                            Id = 19,
                            Address = "1616 Cherrywood St",
                            Country = "Japan",
                            Description = "Modern loft in a bustling area.",
                            Price = 300000.0
                        },
                        new
                        {
                            Id = 20,
                            Address = "1717 Willowwood St",
                            Country = "South Korea",
                            Description = "Stylish home with advanced features.",
                            Price = 500000.0
                        });
                });

            modelBuilder.Entity("Globomantics.Models.Bid", b =>
                {
                    b.HasOne("Globomantics.Models.House", "House")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });
#pragma warning restore 612, 618
        }
    }
}
